function D=spm_opm_attach_leadfield(label,G,val,D)
%
% Wrapper function to save lead field matrices generated by FieldTrip to an
% SPM-friendly format. Lead fields will also be attributed with the SPM
% object.
%
% Labels for the channels MUST match those with which the lead field was
% generated.
%
% Save the lead field to disk
% Example usage with FieldTrip:
%
% cfg             = [];
% cfg.vol         = headmodel;
% cfg.grid        = sourcemodel;
% cfg.grad        = data.grad;
% cfg.channel     = data.grad.label;
% cfg.normalize   = 'no';
% cfg.reducerank  = 2;
% gridLF = ft_prepare_leadfield(cfg);
% 
% % Extract the leadfield
% G = gridLF.leadfield(gridLF.inside);
%
% % Attach lead field to D object
% spm_opm_attach_leadfield(data.grad.label,G,1,D)

SVNid = '$Rev: 7118 $';
spm('FnBanner',mfilename,SVNid);
fprintf('Attaching lead field to D object and saving to disk...\n')
D.inv{val}.gainmat = ['SPMgainmatrix_' spm_file(D.fname, 'basename') '_' num2str(val) '.mat'];
save(fullfile(D.path, D.inv{val}.gainmat), 'G', 'label', spm_get_defaults('mat.format'));
fprintf('Done.\n')
end